from kubernetes import client, config
from pprint import pprint

config.load_incluster_config()
# Configure API key authorization: BearerToken
# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
# configuration.api_key_prefix['authorization'] = 'Bearer'

# Defining host is optional and default to http://localhost

# Enter a context with an instance of the API kubernetes.client
api_instance=client.CoreV1Api()
# Create an instance of the API class
pretty = 'true' # str | If 'true', then the output is pretty printed. (optional)
#allow_watch_bookmarks = True # bool | allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. (optional)
#_continue = '_continue_example' # str | The continue option should be set when retrieving more results from the server. Since this value is server defined, kubernetes.clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the kubernetes.client needs a consistent list, it must restart their list without the continue field. Otherwise, the kubernetes.client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications. (optional)
#field_selector = 'field_selector_example' # str | A selector to restrict the list of returned objects by their fields. Defaults to everything. (optional)
#label_selector = 'label_selector_example' # str | A selector to restrict the list of returned objects by their labels. Defaults to everything. (optional)
limit = 56 # int | limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and kubernetes.clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, kubernetes.clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a kubernetes.client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned. (optional)
#resource_version = 'resource_version_example' # str | resourceVersion sets a constraint on what resource versions a request may be served from. See https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions for details.  Defaults to unset (optional)
#resource_version_match = 'resource_version_match_example' # str | resourceVersionMatch determines how resourceVersion is applied to list calls. It is highly recommended that resourceVersionMatch be set for list calls where resourceVersion is set See https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions for details.  Defaults to unset (optional)
#send_initial_events = True # bool | `sendInitialEvents=true` may be set together with `watch=true`. In that case, the watch stream will begin with synthetic events to produce the current state of objects in the collection. Once all such events have been sent, a synthetic \"Bookmark\" event  will be sent. The bookmark will report the ResourceVersion (RV) corresponding to the set of objects, and be marked with `\"k8s.io/initial-events-end\": \"true\"` annotation. Afterwards, the watch stream will proceed as usual, sending watch events corresponding to changes (subsequent to the RV) to objects watched.  When `sendInitialEvents` option is set, we require `resourceVersionMatch` option to also be set. The semantic of the watch request is as following: - `resourceVersionMatch` = NotOlderThan   is interpreted as \"data at least as new as the provided `resourceVersion`\"   and the bookmark event is send when the state is synced   to a `resourceVersion` at least as fresh as the one provided by the ListOptions.   If `resourceVersion` is unset, this is interpreted as \"consistent read\" and the   bookmark event is send when the state is synced at least to the moment   when request started being processed. - `resourceVersionMatch` set to any other value or unset   Invalid error is returned.  Defaults to true if `resourceVersion=\"\"` or `resourceVersion=\"0\"` (for backward compatibility reasons) and to false otherwise. (optional)
timeout_seconds = 56 # int | Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity. (optional)
#watch = True # bool | Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion. (optional)

try:
    api_response = api_instance.list_node(pretty=pretty, timeout_seconds=timeout_seconds).items[0].status #this is the memory information i need so allocatable is free cpu sometimes it comes in kibibytes which is horrible
    pprint(api_response)
except client.rest.ApiException as e:
    print("Exception when calling CoreV1Api->list_node: %s\n" % e)


#example of full node list for future reference
# {'api_version': 'v1',
#  'items': [{'api_version': None,
#             'kind': None,
#             'metadata': {'annotations': {'kubeadm.alpha.kubernetes.io/cri-socket': 'unix:///var/run/cri-dockerd.sock',
#                                          'node.alpha.kubernetes.io/ttl': '0',
#                                          'volumes.kubernetes.io/controller-managed-attach-detach': 'true'},
#                          'creation_timestamp': datetime.datetime(2022, 9, 20, 12, 1, 49, tzinfo=tzlocal()),
#                          'deletion_grace_period_seconds': None,
#                          'deletion_timestamp': None,
#                          'finalizers': None,
#                          'generate_name': None,
#                          'generation': None,
#                          'labels': {'beta.kubernetes.io/arch': 'amd64',
#                                     'beta.kubernetes.io/os': 'linux',
#                                     'kubernetes.io/arch': 'amd64',
#                                     'kubernetes.io/hostname': 'docker-desktop',
#                                     'kubernetes.io/os': 'linux',
#                                     'node-role.kubernetes.io/control-plane': '',
#                                     'node.kubernetes.io/exclude-from-external-load-balancers': ''},
#                          'managed_fields': [{'api_version': 'v1',
#                                              'fields_type': 'FieldsV1',
#                                              'fields_v1': {'f:metadata': {'f:annotations': {'.': {},
#                                                                                             'f:volumes.kubernetes.io/controller-managed-attach-detach': {}},
#                                                                           'f:labels': {'.': {},
#                                                                                        'f:beta.kubernetes.io/arch': {},
#                                                                                        'f:beta.kubernetes.io/os': {},
#                                                                                        'f:kubernetes.io/arch': {},
#                                                                                        'f:kubernetes.io/hostname': {},
#                                                                                        'f:kubernetes.io/os': {}}}},
#                                              'manager': 'kubelet',
#                                              'operation': 'Update',
#                                              'subresource': None,
#                                              'time': datetime.datetime(2022, 9, 20, 12, 1, 49, tzinfo=tzlocal())},
#                                             {'api_version': 'v1',
#                                              'fields_type': 'FieldsV1',
#                                              'fields_v1': {'f:metadata': {'f:annotations': {'f:kubeadm.alpha.kubernetes.io/cri-socket': {}},
#                                                                           'f:labels': {'f:node-role.kubernetes.io/control-plane': {},
#                                                                                        'f:node.kubernetes.io/exclude-from-external-load-balancers': {}}}},
#                                              'manager': 'kubeadm',
#                                              'operation': 'Update',
#                                              'subresource': None,
#                                              'time': datetime.datetime(2022, 9, 20, 12, 1, 50, tzinfo=tzlocal())},
#                                             {'api_version': 'v1',
#                                              'fields_type': 'FieldsV1',
#                                              'fields_v1': {'f:metadata': {'f:annotations': {'f:node.alpha.kubernetes.io/ttl': {}}}},
#                                              'manager': 'kube-controller-manager',
#                                              'operation': 'Update',
#                                              'subresource': None,
#                                              'time': datetime.datetime(2023, 1, 12, 18, 2, 40, tzinfo=tzlocal())},
#                                             {'api_version': 'v1',
#                                              'fields_type': 'FieldsV1',
#                                              'fields_v1': {'f:status': {'f:addresses': {'k:{"type":"InternalIP"}': {'f:address': {}}},
#                                                                         'f:conditions': {'k:{"type":"DiskPressure"}': {'f:lastHeartbeatTime': {},
#                                                                                                                        'f:lastTransitionTime': {},
#                                                                                                                        'f:message': {},
#                                                                                                                        'f:reason': {},
#                                                                                                                        'f:status': {}},
#                                                                                          'k:{"type":"MemoryPressure"}': {'f:lastHeartbeatTime': {},
#                                                                                                                          'f:lastTransitionTime': {},
#                                                                                                                          'f:message': {},
#                                                                                                                          'f:reason': {},
#                                                                                                                          'f:status': {}},
#                                                                                          'k:{"type":"PIDPressure"}': {'f:lastHeartbeatTime': {},
#                                                                                                                       'f:lastTransitionTime': {},
#                                                                                                                       'f:message': {},
#                                                                                                                       'f:reason': {},
#                                                                                                                       'f:status': {}},
#                                                                                          'k:{"type":"Ready"}': {'f:lastHeartbeatTime': {},
#                                                                                                                 'f:lastTransitionTime': {},
#                                                                                                                 'f:message': {},
#                                                                                                                 'f:reason': {},
#                                                                                                                 'f:status': {}}},
#                                                                         'f:images': {},
#                                                                         'f:nodeInfo': {'f:bootID': {}}}},
#                                              'manager': 'kubelet',
#                                              'operation': 'Update',
#                                              'subresource': 'status',
#                                              'time': datetime.datetime(2023, 8, 30, 12, 21, 54, tzinfo=tzlocal())}],
#                          'name': 'docker-desktop',
#                          'namespace': None,
#                          'owner_references': None,
#                          'resource_version': '1065952',
#                          'self_link': None,
#                          'uid': '7c8348a6-1155-4b88-a53e-86bf7669731c'},
#             'spec': {'config_source': None,
#                      'external_id': None,
#                      'pod_cid_rs': None,
#                      'pod_cidr': None,
#                      'provider_id': None,
#                      'taints': None,
#                      'unschedulable': None},
#             'status': {'addresses': [{'address': '192.168.65.4',
#                                       'type': 'InternalIP'},
#                                      {'address': 'docker-desktop',
#                                       'type': 'Hostname'}],
#                        'allocatable': {'cpu': '24',
#                                        'ephemeral-storage': '242541353378',
#                                        'hugepages-1Gi': '0',
#                                        'hugepages-2Mi': '0',
#                                        'memory': '26073192Ki',
#                                        'pods': '110'},
#                        'capacity': {'cpu': '24',
#                                     'ephemeral-storage': '263174212Ki',
#                                     'hugepages-1Gi': '0',
#                                     'hugepages-2Mi': '0',
#                                     'memory': '26175592Ki',
#                                     'pods': '110'},
#                        'conditions': [{'last_heartbeat_time': datetime.datetime(2023, 8, 30, 12, 21, 54, tzinfo=tzlocal()),
#                                        'last_transition_time': datetime.datetime(2023, 1, 12, 18, 3, 10, tzinfo=tzlocal()),
#                                        'message': 'kubelet has sufficient '
#                                                   'memory available',
#                                        'reason': 'KubeletHasSufficientMemory',
#                                        'status': 'False',
#                                        'type': 'MemoryPressure'},
#                                       {'last_heartbeat_time': datetime.datetime(2023, 8, 30, 12, 21, 54, tzinfo=tzlocal()),
#                                        'last_transition_time': datetime.datetime(2023, 1, 12, 18, 3, 10, tzinfo=tzlocal()),
#                                        'message': 'kubelet has no disk '
#                                                   'pressure',
#                                        'reason': 'KubeletHasNoDiskPressure',
#                                        'status': 'False',
#                                        'type': 'DiskPressure'},
#                                       {'last_heartbeat_time': datetime.datetime(2023, 8, 30, 12, 21, 54, tzinfo=tzlocal()),
#                                        'last_transition_time': datetime.datetime(2023, 1, 12, 18, 3, 10, tzinfo=tzlocal()),
#                                        'message': 'kubelet has sufficient PID '
#                                                   'available',
#                                        'reason': 'KubeletHasSufficientPID',
#                                        'status': 'False',
#                                        'type': 'PIDPressure'},
#                                       {'last_heartbeat_time': datetime.datetime(2023, 8, 30, 12, 21, 54, tzinfo=tzlocal()),
#                                        'last_transition_time': datetime.datetime(2023, 1, 12, 18, 3, 10, tzinfo=tzlocal()),
#                                        'message': 'kubelet is posting ready '
#                                                   'status',
#                                        'reason': 'KubeletReady',
#                                        'status': 'True',
#                                        'type': 'Ready'}],
#                        'config': None,
#                        'daemon_endpoints': {'kubelet_endpoint': {'port': 10250}},
#                        'images': [{'names': ['<none>@<none>', '<none>:<none>'],
#                                    'size_bytes': 1057438812},
#                                   {'names': ['<none>@<none>', '<none>:<none>'],
#                                    'size_bytes': 1057438662},
#                                   {'names': ['<none>@<none>', '<none>:<none>'],
#                                    'size_bytes': 1057438657},
#                                   {'names': ['<none>@<none>', '<none>:<none>'],
#                                    'size_bytes': 1057438654},
#                                   {'names': ['<none>@<none>', '<none>:<none>'],
#                                    'size_bytes': 1057438652},
#                                   {'names': ['test:latest'],
#                                    'size_bytes': 1057438585},
#                                   {'names': ['hubproxy.docker.internal:5000/docker/desktop-kubernetes@sha256:ac6f48414c14f8562f1bc7d526994a7f34c816cfdaa85e11691386a59e64afa3',
#                                              'hubproxy.docker.internal:5000/docker/desktop-kubernetes:kubernetes-v1.25.0-cni-v1.1.1-critools-v1.24.2-cri-dockerd-v0.2.5-1-debian'],
#                                    'size_bytes': 363303370},
#                                   {'names': ['k8s.gcr.io/etcd:3.5.4-0'],
#                                    'size_bytes': 299520781},
#                                   {'names': ['registry.k8s.io/ingress-nginx/controller@sha256:34ee929b111ffc7aa426ffd409af44da48e5a0eea1eb2207994d9e0c0882d143'],
#                                    'size_bytes': 263629714},
#                                   {'names': ['k8s.gcr.io/kube-apiserver:v1.25.0'],
#                                    'size_bytes': 127711996},
#                                   {'names': ['k8s.gcr.io/kube-controller-manager:v1.25.0'],
#                                    'size_bytes': 117095443},
#                                   {'names': ['ghcr.io/helm/tiller@sha256:4c43eb385032945cad047d2350e4945d913b90b3ab43ee61cecb32a495c6df0f',
#                                              'ghcr.io/helm/tiller:v2.17.0'],
#                                    'size_bytes': 88062800},
#                                   {'names': ['k8s.gcr.io/kube-proxy:v1.25.0'],
#                                    'size_bytes': 61683733},
#                                   {'names': ['k8s.gcr.io/kube-scheduler:v1.25.0'],
#                                    'size_bytes': 50580512},
#                                   {'names': ['k8s.gcr.io/coredns:v1.9.3'],
#                                    'size_bytes': 48803555},
#                                   {'names': ['docker/desktop-storage-provisioner:v2.0'],
#                                    'size_bytes': 41850220},
#                                   {'names': ['docker/desktop-vpnkit-controller:v2.0'],
#                                    'size_bytes': 21034536},
#                                   {'names': ['k8s.gcr.io/pause:3.8'],
#                                    'size_bytes': 711184}],
#                        'node_info': {'architecture': 'amd64',
#                                      'boot_id': '755a89c8-682e-46d6-bde7-1c6d93aaff75',
#                                      'container_runtime_version': 'docker://20.10.17',
#                                      'kernel_version': '5.10.16.3-microsoft-standard-WSL2',
#                                      'kube_proxy_version': 'v1.25.0',
#                                      'kubelet_version': 'v1.25.0',
#                                      'machine_id': 'ac1b2762-5105-439c-ac07-af317d46d45e',
#                                      'operating_system': 'linux',
#                                      'os_image': 'Docker Desktop',
#                                      'system_uuid': 'ac1b2762-5105-439c-ac07-af317d46d45e'},
#                        'phase': None,
#                        'volumes_attached': None,
#                        'volumes_in_use': None}}],
#  'kind': 'NodeList',
#  'metadata': {'_continue': None,
#               'remaining_item_count': None,
#               'resource_version': '1065959',
#               'self_link': None}}
