apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "main-helm-chart.fullname" . }}-daemon
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "main-helm-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "main-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "main-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "main-helm-chart.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-daemon
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.daemon.image.repository }}:{{ .Values.daemon.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.daemon.image.pullPolicy }}
          env:
          - name: MAIN-SERVICE
            value: {{ include "main-helm-chart.fullname" . }}{{ .Values.main_component.service.name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      initContainers:
        - name: init-main-service
          image: busybox:1.28
          command:
            - sh
            - -c
            - >
              until nslookup {{ include "main-helm-chart.fullname" . }}{{ .Values.main_component.service.name }};
              do echo waiting for {{ include "main-helm-chart.fullname" . }}{{ .Values.main_component.service.name }};
              sleep 2;
              done
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}