apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main-helm-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "main-helm-chart.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.main_component.labels }}
    {{ $key }}: {{ $val}}
    {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "main-helm-chart.selectorLabels" . | nindent 6 }}
      {{- range $key, $val := .Values.main_component.labels }}
      {{ $key }}: {{ $val}}
      {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "main-helm-chart.selectorLabels" . | nindent 8 }}
        {{- range $key, $val := .Values.main_component.labels }}
        {{ $key }}: {{ $val}}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "main-helm-chart.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.main_component.image.repository }}:{{ .Values.main_component.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.main_component.image.pullPolicy }}
          env:
          - name: DAEMON-SERVICE
            value: {{ include "main-helm-chart.fullname" . }}{{ .Values.daemon.service.name }}
          - name: DAEMON-SERVICE-PORT
            value: {{ .Values.service.port  | quote}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/kubernetes/my-scheduler
      initContainers:
        - name: init-daemon-service
          image: busybox:1.28
          command:
            - sh
            - -c
            - >
              until nslookup {{ include "main-helm-chart.fullname" . }}{{ .Values.daemon.service.name }};
              do echo waiting for{{ include "main-helm-chart.fullname" . }}{{ .Values.daemon.service.name }};
              sleep 2;
              done
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: my-scheduler-config
