apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: default
data:
  spark-defaults.conf: |
    spark.master=https://kubernetes.docker.internal:6443
    spark.ui.port=4040
    spark.driver.host=spark-driver
    spark.driver.bindAddress=0.0.0.0
    spark.driver.port=29413
    spark.kubernetes.pyspark.pythonVersion=3
    spark.pyspark.python=/usr/bin/python3
    spark.kubernetes.container.image=name of the image
    spark.kubernetes.namespace=default
    spark.kubernetes.executor.request.cores=1.0
    spark.executor.instances=8
