
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    k8s-app: spark
  name: spark
  namespace: default

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/vv1
kind: Role
metadata:
  namespace: default
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]