apiVersion: v1
kind: Service
metadata:
  name: spark-driver
  namespace: default
spec:
  clusterIP: None
  selector:
    job: spark-job
  ports:
  - port: 29413
    protocol: TCP
    targetPort: 29413
  sessionAffinity: None
  type: ClusterIP